//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Trans
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
